import AppKit

/// Identifies sensitive data markers placed by password managers (ConcealedType)
public enum PasteboardConcealed {
    /// Standard macOS pasteboard types indicating password manager concealment
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.dstoecker.x-passwords"),
        NSPasteboard.PasteboardType("net.sourceforge.keepassxc"),
        NSPasteboard.PasteboardType("com.bitwarden.desktop")
    ]
    
    /// Checks if the current pasteboard contents are marked as concealed or sensitive
    public static func isConcealed(pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        for type in types {
            if concealedTypes.contains(type) {
                return true
            }
        }
        return false
    }
}
